/** 面向玩家的界面文案 */
export const PLAYER_COPY = {
  gameTitle: '梦想世界',
  battleTitle: '仙途演武',
  battleTurn: (turn: number) => `第 ${turn} 回合`,
  battleEntering: '双方照面…',
  battleFighting: '交锋正酣',
  battleSettling: '清点战利…',
  battleStart: '挑战强敌',
  battleStartShort: '开战',
  battleAgain: '再战一局',
  battleAgainShort: '再战',
  battleWinShort: '胜',
  battleLoseShort: '败',
  battleStandbyLabel: '待战',
  battleWinner: '胜者',
  bag: '行囊',
  manualReward: (exp: number, gold: number) => `战利 +${exp} 经验 · +${gold} 金币`,
  levelUp: '境界精进！',
  logout: '重走江湖',
  settings: '设置',
  settingsTitle: '系统设置',
  logoutSection: '江湖行藏',
  logoutHint: '断开当前角色，重新择名入局。',
  logoutConfirmBody: '当前进度将与本设备断开，需重新创立角色。此举不可撤回，确定要继续吗？',
  logoutConfirm: '确定重走',
  cancel: '再想想',
  loadingWorld: '踏入仙途…',
  connectionFailed: '暂时无法进入世界，请稍后再试',
  retry: '再试一次',
  opponentFallback: '关外妖兽',
  actorLoadFailed: '形象未能显现，请刷新后再试',
  journeySection: '凡尘涟漪',
  journeyOpenDetail: '查看详情',
  journeyStoryPending: '剧情有待推进 · 点击查看',
  storyContinue: '继续',
  questSummary: '当下境遇',
  questStory: '剧情',
  questFoe: '当前敌手',
  questObjectives: '行事要点',
  questReward: '完成赏赉',
  questStage: (stage: number) => `第 ${stage} 关`,
  questMapLandmarks: '地标',
  questMapPhase: (phase: string, map: string) => `${phase} · ${map}`,
  mapTeleport: '传送',
  mapTravelOpen: '展开卷轴',
  mapTravelBoss: '关底敌手',
  mapTravelRoute: '行路一览',
  mapTravelHere: '在此',
  mapTravelNeedBoss: '需先击败关底敌手，方可启程',
  mapTravelReady: '关底已破，可启程前往下一站',
  mapTravelAdvance: '启程前行',
  mapTravelHint: '点击地图查看卷轴',
  mapTravelClearedBadge: '可启程',
  mapJourneyTeaser: '前路迷雾',
  mapJourneyUnknown: '未探',
  soloTravelBadge: '独行侠 · 孤身一人',
  soloTravelHint: '此刻只有你一人在路上。待立宗开派，方可招募同道、共修共战。',
  sectRecruitLocked: '立宗后可招募弟子',
  sectRecruitUnlocked: '宗门已立 · 可招募弟子',
} as const
