import type { BattleUnitConfig } from './battle.types'

export const ACTION_GAUGE_THRESHOLD = 100

export const PLAYER_BATTLE_UNIT: BattleUnitConfig = {
  side: 'player',
  id: 'sanim_224041',
  label: '修真者',
  skeleton: '/放置觉醒spine/sanim/sanim_224041/sanim_224041.json',
  scale: 0.68,
  fitHeightWeight: 0.58,
  spawnXRatio: 0.12,
  xRatio: 0.34,
  yRatio: 0.88,
  faceDirection: 1,
  combatAdvanceRatio: 0.034,
  maxHp: 1200,
  attack: 95,
  defense: 3,
  spiritPower: 150,
  speed: 22,
  skillCooldown: 3,
  combatStyle: 'hero',
  animations: {
    idle: 'holdon',
    run: 'move',
    attack: 'att',
    skill: 'skill',
    ultimate: 'ultimateskill',
    hit: 'behit',
    death: 'death',
  },
}

export const ENEMY_BATTLE_UNIT: BattleUnitConfig = {
  side: 'enemy',
  id: 'mh_1107',
  label: '关外妖兽',
  skeleton: '/monsters/mh_1107/mh_1107.skel',
  scale: 0.74,
  fitHeightWeight: 0.55,
  spawnXRatio: 0.88,
  xRatio: 0.54,
  yRatio: 0.88,
  faceDirection: -1,
  combatAdvanceRatio: 0.03,
  maxHp: 95,
  attack: 16,
  defense: 6,
  spiritPower: 12,
  speed: 12,
  skillCooldown: 4,
  combatStyle: 'brute',
  animations: {
    idle: 'act_idle',
    run: 'act_run',
    attack: 'act_skill_01',
    skill: 'act_skill_02',
    ultimate: 'act_skill_02',
    hit: 'act_hit',
    death: 'act_die',
  },
}
